### ISSUE TITLE
Use generic deploy.sh everywhere

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#11]
With the groundwork in #6 landed, we now need to make sure all standards start using it. We also need to further tweak the script for that to happy completely, since a couple standards have additional requirements.

These are left:

- [x] URL (needs extra resources for master)
- [x] XMLHttpRequest (needs extra resources everywhere)
- [x] Encoding (needs extra resources everywhere)
- [x] Streams (needs emu-algify step)
- [x] Console (needs extra resources everywhere)
- [x] Compatibility (needs extra resources everywhere)

(There's also Books, Figures, Loader, and HTML Differences.)

**Comment by annevk** [comment]
I updated OP with what is remaining. They all require changes to the deploy script.

**Comment by domenic** [comment]
I believe URL no longer has extra resources and so could be converted.

**Comment by annevk** [comment]
URL has `.htaccess`.

**Comment by foolip** [comment]
For encoding, in addition to the extra resources, there's also a script (visualize.py) that needs to run.

Perhaps rather than the EXTRA_FILES approach in https://github.com/whatwg/whatwg.org/pull/68 we should let the shared deploy.sh invoke an optional per-repository post-build.sh that takes as an argument a directory and a mode (master/commit-snapshot/branch-snapshot) to perform extra steps?

To enable commit snapshots and shared deploy for books and figures, we could also look for a build.sh, which if present is used instead of https://api.csswg.org/bikeshed/.

How does that sound, is there anything that still couldn't share the common deploy script then?

**Comment by domenic** [comment]
>  optional per-repository post-build.sh that takes as an argument a directory and a mode

I think I like this, although the simplicity of EXTRA_FILES is also quite nice, and maybe should be left as a 90% case?

> To enable commit snapshots and shared deploy for books and figures, we could also look for a build.sh, which if present is used instead of https://api.csswg.org/bikeshed/.

That seems OK, although I am not too concerned about Books and Figures.

> is there anything that still couldn't share the common deploy script then?

We should check that the Node stuff in console/streams works here. I think a post-build.sh would do the trick, but I am unsure why I used index.intermediate.html instead of index.html. index.intermediate.html does not fit well in a post-build framework.

**Comment by foolip** [comment]
So, leaving non-Bikeshed specs (including HTML) to the side for the moment, perhaps instead of a file by a specific name, we have an EXTRA_BUILD_STEP that could either do something simple, or invoke a script for something more complicated. I'll give it a shot.

**Comment by foolip** [comment]
@annevk, for encoding the HTML checker bits are also a bit special, with a CHECKER_PARAMS in .travis.yml. Is there any behavior there that needs to be preserved, or is the shared checker logic OK?

**Comment by annevk** [comment]
@foolip that needs to be preserved. We added it to ensure we don't miss any actual errors.

**Comment by foolip** [comment]
Are these errors specific to encoding, or can it be moved to the common deploy script?

**Comment by annevk** [comment]
Specific warnings. We'd probably not want to allow those warnings elsewhere.

**Comment by foolip** [comment]
Is it also important that the checker runs on all changes and not just on master deploys as in the common build script? If there's too much to fix, I'll probably just set up double-deploy in encoding's deploy.sh instead :)

**Comment by annevk** [comment]
We should maybe fix the common script to run the checker on PRs as well. That's the point where you'd want to catch any validation errors.

**Comment by foolip** [comment]
Updated the description about console, now only extra images are needed.

And I was wrong about the checker only running on master deploys, it runs for all Travis jobs that attempt to deploy.

**Comment by domenic** [comment]
This has been done, woohoo!
