### ISSUE TITLE
TPAC 2020 participation?

### ISSUE THREAD

**Issue by dbaron** [whatwg/meta#171]
A virtual TPAC 2020 is currently being planned.  This is likely to look pretty different from previous in-person TPACs (perhaps focusing more on the functions of TPAC other than regular working group meeting time, or perhaps pushing that to adjacent weeks).  However, it's still worth thinking about how the WHATWG community should participate in this TPAC and what we'd like to ask for in terms of meetings, discussions, presentations, or other sessions.

**Comment by foolip** [comment]
@annevk the WHATWG SG is meeting with W3C management next week and the plan is to request some time at TPAC. How much time do you think makes sense, and do you have specific topics in mind?

**Comment by annevk** [comment]
I'm not sure if I'm too late at this point, but it might make sense to have some time (an hour, perhaps more for bigger) per standard (DOM/HTML, Fetch, Storage, Streams) for either technical discussion or more high-level Q&A. I don't think we need to include all standards as some are effectively in maintenance mode.

**Comment by travisleithead** [comment]
Here's the latest [guidelines on TPAC Group Meetings](https://www.w3.org/wiki/TPAC/2020/GroupMeetings). W3C management has kindly invited the WHATWG to participate as well. (Since we are not W3C Working Groups, Community Groups, etc.) Participation primarily means having any of our scheduled virtual face-to-face meetings listed in a master table of group meetings that will be associated with the Virtual TPAC event. The reason to be listed is to encourage wider community participation by easily enabling observers and other TPAC participants to discover and attend our meetings.

We need only determine if a Workstream desires to have a virtual meeting, and then pick a time to schedule said meeting. Two weeks are being reserved; one for Joint virtual meetings (e.g., cross-group meetings) on the 12th - 16th of Oct., and the other for breakout sessions traditionally held on the Wednesday of TPAC week (26th - 30th of Oct.). These are illustrated in the figure below. Unless we specifically plan to coordinate a meeting with another W3C group, or focus a meeting on a particular "breakout" topic, we should avoid these two scheduled weeks. Any other weeks are OK to schedule (including in September and November), though [consult the wiki table](https://www.w3.org/wiki/TPAC/2020/GroupMeetings#WG.2FIG.2FBG_Group_Meetings_details) for existing confirmed meeting times that might overlap.
![image](https://user-images.githubusercontent.com/2152696/90670667-61675880-e208-11ea-9624-a5c3d2c1b4be.png)

Some notable W3C groups have already confirmed meeting dates and times (in UTC):
* CSS: 19, 20 Oct. @ 2000 - 2300 and 22, 23 Oct. @ 1400 - 1700
* Web Perf: 19, 20, 21, 22 Oct. @ 1600 - 1900

(I suspect the 19 - 23 will fill-up quick, and recommend an alternative week to avoid conflicts.)

**Comment by travisleithead** [comment]
@annevk it sounds like you were interested in seeing at least those WS mentioned have a chance to meet. @domenic what do you think?

As far as good UTC times to meet:
* Europe/US friendly start time 1500 - 1600
* Europe/Asia friendly start time: 0700 - 0800
* US/Asia friendly start time: 2200 - 2300

**Comment by domenic** [comment]
> @domenic what do you think?

In general I'm not much of a "WHATWG meetings" person, but @annevk's idea of kind of "office hours" for specs makes sense to me, and I'd be happy to endorse and/or attend them.

Concretely, I think any HTML office hours will have plenty of attendance and discussion, based on past TPAC experiences.

For other specs, there are potentially interesting topics in Fetch, Infra, Storage, and Streams. But, I think it'd be worth getting some indication of community interest (e.g. posting an agenda-gathering issue on each standard's repo), with the option to cancel if it turns out nobody has anything pressing to talk about. Or maybe morph them into a boring issue-tracker-triaging session.

I omitted DOM because I think most exciting things happening there are in web components, which I assume will meet separately.

**Comment by annevk** [comment]
I filed issues to determine interest.

**Comment by annevk** [comment]
https://github.com/whatwg/storage/issues/113 has some folks who are interested in meeting up. If it's only Storage that could probably also be organized separately, though. What do you all think? (Are we still within the time limit?)
