### ISSUE TITLE
Moving specs to modern infrastructure [missing: html-differences]

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#2]
Excluding HTML, since it is a special duckling, all specs should ideally:

- Be on Bikeshed
- Not check their source files into the repo, but auto-deploy via Travis
- Deploy commit snapshots
- Include file-issue.js, commit-snapshot-shortcut-key.js, and dfn.js. (Or, instead of dfn.js, we should use Bikeshed's generated definition panels.)

If all of these become true we can start making some nice assumptions, e.g. we can move some script elements into our Bikeshed boilerplate.

What's missing?

- [x] Fullscreen, Notifications, Mimesniff, Storage, Quirks
  - Still check in build output
  - Missing commit snapshots and commit-snapshot-shortcut-key.js
- [x] XHR
  - Still checks in build output
  - Missing commit snapshots and commit-snapshot-shortcut-key.js
  - Still on Anolis; see https://github.com/whatwg/xhr/pull/97
- [x] Compat
  - Still checks in build output
  - Missing commit snapshots and commit-snapshot-shortcut-key.js
  - dfn.js is in the footer, confusingly
- [x] Console
  - Missing commit snapshots and commit-snapshot-shortcut-key.js (but does not check in build output)
  - Missing dfn.js
  - Both being fixed; see https://github.com/whatwg/console/pull/83
- [x] Streams
  - Is using Bikeshed's definition generator instead of dfn.js (fixed in https://github.com/whatwg/streams/commit/421e621ad7a842c65b35ec68443784ae0e0d8ec4)
- [ ] HTML differences from HTML4
  - Uses Anolis https://github.com/whatwg/html-differences/issues/2
  - No Travis goodness either

**Comment by annevk** [comment]
Another thing I've started doing with help from @sideshowbarker is running the HTML checker on the output. That's quite nice to have.

**Comment by annevk** [comment]
https://github.com/whatwg/fullscreen/pull/73
https://github.com/whatwg/notifications/pull/91
https://github.com/whatwg/mimesniff/pull/17
https://github.com/whatwg/storage/pull/40

**Comment by annevk** [comment]
You'll have to do Console. I don't have access to that server.

**Comment by annevk** [comment]
Books and Figures are also missing I just realized. @foolip and I are looking into that.

**Comment by foolip** [comment]
We ended up not doing that, because it would require first converting to Bikeshed. I think we should leave it be for now.

**Comment by zcorpan** [comment]
IIRC main problem with html-differences is that it cross-references lots of terms from HTML that HTML doesn't properly export.

**Comment by tabatkins** [comment]
Books and Figures are also not web-relevant specs; Håkon moved them out of the CSSWG when we tried to make him cut the spec to things browsers were actually willing to touch.

**Comment by foolip** [comment]
From poking around in https://github.com/whatwg/misc-server/issues/7, I've found these *.spec.whatwg.org and *.idea.whatwg.org that don't use https://resources.whatwg.org/build/deploy.sh but rather some other deploy.sh:
* [books.idea.whatwg.org](https://books.idea.whatwg.org) (simple, no snapshots)
* [compat.spec.whatwg.org](https://compat.spec.whatwg.org) (extra *.png)
* [console.spec.whatwg.org](https://console.spec.whatwg.org) (uses node)
* [encoding.spec.whatwg.org](https://encoding.spec.whatwg.org) (extra *.txt *json *.css)
* [figures.idea.whatwg.org](https://figures.idea.whatwg.org) (simple, no snapshots)
* [html.spec.whatwg.org](https://html.spec.whatwg.org) (uses html-build)
* [streams.spec.whatwg.org](https://streams.spec.whatwg.org) (uses node)
* [url.spec.whatwg.org](https://url.spec.whatwg.org) (not sure why)

How much unification is worth attempting here. One thing that that'd help compat and encoding is to teach https://resources.whatwg.org/build/deploy.sh about an `EXTRA_FILES` variable that could be set to extra files to copy along.

Beyond that, having to change the deploy servers in so many places is a bit of effort. Would it make sense to separate the build and the deploy, so that the deploy bits (decoding the ssh key, rsync) are shared between more scripts?

**Comment by domenic** [comment]
@foolip, it looks like you're basically discussing https://github.com/whatwg/meta/issues/11. This issue was meant to be more about the actual spec content.

**Comment by foolip** [comment]
Oh, that explains why the lists in this issue didn't make as much sense as I though they should. Thanks :)

**Comment by annevk** [comment]
This is fixed by https://github.com/whatwg/misc-server/issues/100.
