### ISSUE TITLE
wiki: CAPTCHA is broken (shown for new external links)

### ISSUE THREAD

**Issue by twifkak** [whatwg/meta#203]
When adding an external link to a [wiki](https://wiki.whatwg.org/) page, I am presented with the text:

>  Your edit includes new external links. To protect the wiki against automated spam, we kindly ask you to solve the following CAPTCHA:

And then no CAPTCHA. This fails closed -- I cannot submit the change.

The JS console has a bunch of errors. At least one seems relevant:

```
Uncaught Error: Missing required parameters: sitekey
    M https://www.gstatic.com/recaptcha/releases/2Mfykwl2mlvyQZQ3PEgoH710/recaptcha__en.js:318
```

![Screenshot of error with JS console open](https://lh3.googleusercontent.com/pw/ACtC-3daAY9rMr0HgSIHLdQzuKpwA6UBGfDpQNKtRypXvPD5YszDw0wNAlRuwUONWpXlkg69eTMFIWaiWL0L4Ho8YQ7WzoDkeg5bWBiOyerxtg67onMzg_ZrzJ653OuRHuuQiChDv_IN6RAkThqBbH8m-qfc=w2554-h960-no?authuser=0)

**Comment by annevk** [comment]
cc @GPHemsley

**Comment by GPHemsley** [comment]
Well that's not good. I'll take a look this weekend.

(Sorry for the delay. Pinging me on GitHub is not currently a productive way to get my attention, unfortunately.)

**Comment by GPHemsley** [comment]
Apparently this has been broken since we switched from using ReCaptcha to using ReCaptchaNoCaptcha, as the config variables supplying the public and private keys have different names (`$wgReCaptchaPublicKey`/`$wgReCaptchaPrivateKey` vs. `$wgReCaptchaSiteKey`/`$wgReCaptchaSecretKey`).

This should now be fixed.
