### ISSUE TITLE
Notify MDN about changes

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#62]
I talked with @chrisdavidmills about notifying MDN about changes to standards. The easiest way to do this would be with a label that MDN can track (at least until MDN moves to GitHub at which point we could consider filing an issue there or have it filed automatically).

Suggestion: `mdn-relevant`. The expectation here is that MDN would take care of tracking whether they have documentation for it or not.

**Comment by domfarolino** [comment]
I really like this, I've found it tough to remember change/update some MDN stuff in the past.

**Comment by foolip** [comment]
Maybe "needs documentation" to match some of the other labels?

@jpmedley, WDYT?

**Comment by domfarolino** [comment]
@foolip My only concern with that is, to me it almost indicates we’d block merging on waiting for documentation. Do we want this, and do others perceive it that way or is that just me?

I think something like mdn-relavent or effects-documentation is nice because it’s more of a side note for external parties to track and us not to worry about TOO much. Thoughts?

**Comment by foolip** [comment]
The other needs foo labels are blocking, so yes, that's a problem. But if this is a label that will be tracked after issues have already been closed, then removing mdn-relevant also seems weird. It's still relevant :)

Maybe two labels would be better, so that no labels are removed. No ideas about names though.

**Comment by annevk** [comment]
It wouldn't be removed though. It would just stay there. (Modifying labels is tricky in this case as MDN folks are unlikely to have the required GitHub access. That's why we came up with the above suggestion.)

**Comment by foolip** [comment]
How would triage work if no state on our issues changes after the thing has been documented?

**Comment by domfarolino** [comment]
Yeah I feel like we can either have a single label that gets removed from closed issues/PRs once MDN'ers update documentation, or the two labels as @foolip recommends - as in, we add a label like "documentation-addressed/complete" or something when the documentation catches up.

The issue I see with the two-label solution is that it requires MDN'ers that wish to find PRs that require documentation to manually filter through ones that *DON'T* also have the "documentation-complete" label. GitHub does not provide a way through the advanced search UI to search for issues/PRs through label exclusion. It can still be done [this way](https://github.com/isaacs/github/issues/65#issuecomment-43332400) but I'm assuming most don't know about it, and it could be helpful with the two-label soln.

**Comment by foolip** [comment]
I don't remember how I discovered that it worked, but we have a triage process for web-platform-tests to look for issues with some labels but without some others in https://bit.ly/ecosystem-infra-rotation. There are a bunch of people who take part in that and AFAIK it hasn't been a problem that the query can't be created by only clicking things.

**Comment by jpmedley** [comment]
I apologize for the late reply. I've been on vacation.

I have doubts about the usefulness of this. I'm trying to think of a spec
change that wouldn't have documentation impact.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

On Sat, Dec 23, 2017 at 8:20 AM, Philip Jägenstedt <notifications@github.com

**Comment by domfarolino** [comment]
I feel that

1. There are some spec changes that are editorial or documentation-based in nature like [this](https://github.com/whatwg/fetch/pull/620), though these (and ones similar) are probably vastly outnumbered by normative implementation- and test-affecting changes
2. Even then, the number of implementation- and test-affecting changes might be minor/specific enough to not need a documentation change. As in, since the documentation isn't 1:1 with the spec, even small normative changes might not change anything in more general conceptual documentation.

**Comment by snuggs** [comment]
@annevk  i've been helping MDN get up to speed on Github with web components and compatibility.
 (https://github.com/mdn/browser-compat-data/pull/623, https://github.com/mdn/browser-compat-data/pull/627). Is the intent to have "all" of MDN up on Github repositories? 

Thanks for the answer in advance. /cc @chrisdavidmills

**Comment by annevk** [comment]
I think so, long term.

**Comment by jpmedley** [comment]
Have you heard something that I haven't? Let's let Chris answer snuggs
question.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by chrisdavidmills** [comment]
Sorry for being so slow to get to this thread. Xmas vacation and all  ;-)

So my thoughts are that it'd be great to have a way of picking up spec changes that will eventually require documentation changes. This could be the single source of truth, rather than docs changes being identified sometimes by Mozilla, sometimes by Google,  sometimes by MS, etc., on our individual bug trackers. Having a single point of truth seems more efficient to me.

Of course, then we'd have to prioritise documenting these things, which would require checking which things are currently (being) implemented against the bug trackers anyway. This might make it not so efficient after all, unless we could automate it all in one stroke.

I am going to bring this up as a discussion topic at the next MDN product advisory board meeting, to get input from multiple browser vendors on how this could work.

To answer @snuggs, there has no movement on this, but we have certainly talked about moving all of MDN (including all the document content) onto GitHub. The PR model would offer a lot of advantages over our current Wiki model...I can't say much more on this yet though.

**Comment by annevk** [comment]
@chrisdavidmills note that at least for WHATWG Living Standards, the intention is that changes will be picked up by at least two implementation in a short period. We secure implementation support before making changes, effectively.

**Comment by chrisdavidmills** [comment]
@annevk OK, cool - this is useful to consider.

**Comment by foolip** [comment]
One problem we'd need to resolve is that if we mark things as resolved by adding or removing a label (1- or 2-label system) then the MDN people would have to be able to change labels in all the spec repos. And that requires write access, it seems.

Would it work to use issues on an MDN repo instead? That is how we handle missing tests, by filing issues on web-platform-tests.

To make that work well in practice I think the issue filing has to be quite streamlined, maybe with a link to a pre-populated issue ready to file?

**Comment by foolip** [comment]
As for how to know when it's worth documenting, one signal that we could automate is the tests. Since the PRs are normally linked to tests, we could track when those tests begin to pass in any browser take some action, like poke a PR maybe.

**Comment by annevk** [comment]
When I talked with @chrisdavidmills we considered that and therefore came up with a single label that MDN folks would track (and MDN would track whether they handled it or not).

**Comment by foolip** [comment]
OK, that'd certainly work from our side. @chrisdavidmills, how would that work on your side? A big spreadsheet that you auto-populate and burn down, or something?

**Comment by chrisdavidmills** [comment]
@foolip something like that. We already have a big GSheet that we populate using an script from Mozilla's bugzilla when dev-doc-needed keywords are added, so we could probably do something similar here.

**Comment by domfarolino** [comment]
I like those ideas. Is the next step on the WHATWG side to add some text in [LABELS.md](https://github.com/whatwg/meta/blob/master/LABELS.md) explaining the single label that @annevk alluded to in https://github.com/whatwg/meta/issues/62#issuecomment-360996172 ?
