### ISSUE TITLE
list of teams doesn't show up in github UI

### ISSUE THREAD

**Issue by bmeck** [whatwg/meta#82]
It would be nice after multiple misunderstandings of the teams not being shown as GitHub teams that they show up in the GitHub UI like other places show them, users can personally opt to hide their presence on teams if they don't want to be visible.

<img width="705" alt="screen shot 2018-04-11 at 9 21 22 am" src="https://user-images.githubusercontent.com/234659/38622875-d353d108-3d69-11e8-9e12-5ae9aa76a829.png">

**Comment by annevk** [comment]
Note that if I go to https://github.com/nodejs I don't see any teams listed so I suspect the reason you see them is because you're a member (so you might want to remove that screenshot as it reveals (theoretical) confidential information; e.g., I only see 305 people).

So you might just have to join the organization first (which you at most have to ask for in case of WHATWG).

When I go to organization settings for Teams there doesn't seem to be a way to make them public either.

**Comment by bmeck** [comment]
Odd, still need a more visible way to get to these though. Will close this issue but don't see a clear way to direct people to learn about https://github.com/whatwg/meta/blob/master/GITHUB-TEAMS.md

**Comment by annevk** [comment]
How does Node do it?

**Comment by bmeck** [comment]
@annevk Node has tons of public meetings so different workflow and way for people to start getting involved. Youtube, twitter, a calendar are ways of getting announcements when teams are doing things. https://nodejs.org/en/about/community/ might help explain more than I or you could ask the community committee. Node also lists working groups at https://nodejs.org/en/about/working-groups/

**Comment by annevk** [comment]
I guess we should at least document this in the FAQ.

**Comment by domenic** [comment]
Not sure it qualifies as a frequently asked question...

**Comment by annevk** [comment]
We do mention collaboration on GitHub, but we don't really stipulate how to make the most of it anywhere. I think that's worth explaining proactively (and it's come up at least a few times).

**Comment by annevk** [comment]
I haven't really seen this issue reoccur, so closing for now.
