### ISSUE TITLE
Link anchor permanence in specs

### ISSUE THREAD

**Issue by mnot** [whatwg/meta#84]
Hi WHATWG,

It'd be super-helpful if WHATWG had some policy about the permanence of anchors for links in its specifications; this would make it easier for other organisations to reference specific parts of WHATWG specs without fearing that the anchor will disappear.

**Comment by foolip** [comment]
What is the solution in other SDOs? I suspect it is to just leave frozen versions of specs around forever? If so, we can just commit to not breaking URLs like https://dom.spec.whatwg.org/commit-snapshots/618e1f2a076fb96cef407445dac9b8c1d1301531/#interface-customevent

**Comment by mnot** [comment]
I was thinking a policy along the lines of:

- if necessary, have a prefix for anchors that indicate that they're stable
- reuse old stable anchors whenever possible (including section renames)
- when a stable anchor is retired (e.g., because it's moved to another doc), add an appendix with that anchor explaining where it went / what happened
- documenting this somewhere so that people know that they can rely on it

**Comment by mnot** [comment]
@foolip everything I've heard from whatwg folks is that there's a strong preference NOT to reference the commit snapshots.

**Comment by mnot** [comment]
Makes sense to me. I could see a process where:

- Stds org (or someone else?) files a new issue "request for permanent anchor"
- After discussion / whatever you need, it gets promoted
- That gets stored somewhere so it doesn't get lost (special anchor name? Other in-doc metadata? In-doc seems best)
- All of this gets written down somewhere so you can point people at it.

**Comment by annevk** [comment]
I think we should store them in a side-resource and then have the specification build-script ensure the anchors listed can actually be found in the generated copy of the standard and fail if that's not the case. I might even want to use something like that pro-actively (which maybe means we should distinguish between got a request for the anchor and added pro-actively) since I forgot side effects of renaming things at times.

**Comment by domenic** [comment]
I think in-document and checked by Bikeshed would be ideal. (As a slight tangent: for specs that reference us that are in the Bikeshed database, it'd be good to find all references to an anchor.)

Regardless, having something written up in the working mode seems worth working on soon, so @mnot can get back to the folks he is presumably liason-ing for with the good news :)

**Comment by domenic** [comment]
I raised https://github.com/whatwg/sg/pull/72 with a first draft of such a policy. Would love thoughts from both any editors (I pinged them all there) and from folks like @mnot.

**Comment by domfarolino** [comment]
I was going to comment on the PR itself, but thought it might be fitting to bring this up here:

To help an editor find the original issue thread (opened by someone wanting to reference an anchor), if it is either closed or buried somewhere, how do you feel about introducing a new label for [LABELS.md](https://github.com/whatwg/meta/blob/master/LABELS.md) called "anchor-permanence" or something to that effect? Since the PR refers to issues that are *specifically* open for anchor permanence and may need referred to way later on, this may be a good way to weed them out.

**Comment by domfarolino** [comment]
Probably just LABELS.md is my guess. I'm thinking a good chunk of people requesting a permanent anchor will not the proper access to apply a label themselves, so the editors (that already familiar with LABELS.md) will need to do it.

**Comment by domenic** [comment]
This is now done! https://whatwg.org/working-mode#anchors

**Comment by mnot** [comment]
Thanks so much!
