### ISSUE TITLE
Label: clarification vs editorial

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#98]
I noticed Streams has editorial as label. Should we use that everywhere or switch Streams to clarification? Or maybe have both?

cc @ricea

**Comment by ricea** [comment]
In my mind, there's a distinction between the two. I've looked at some examples:

https://github.com/whatwg/streams/issues?utf8=%E2%9C%93&q=label%3Aeditorial vs. https://github.com/whatwg/fetch/issues?utf8=%E2%9C%93&q=label%3Aclarification

Sometimes in Streams we're using "editorial" where "clarification" would be better, but we're also using it a lot for issues around markup and wordsmithing which are not specifically clarifications.

Can we just use "clarification" more on Streams while keeping "editorial" for the rest of the things we're using it for?

**Comment by annevk** [comment]
Yes, perhaps it's worth standardizing on "editorial" then in `labels.json`.

**Comment by domfarolino** [comment]
+1 for adding "editorial" to labels from me

**Comment by domenic** [comment]
I agree with @ricea that there's a distinction, and would be happy to have both. I've kind of shied away from "editorial" sometimes because it's easy to confuse with "non-normative", which is IMO a broader category that also encompasses clarifications or the addition of examples or similar. But as long as we have a clear definition it's fine.

It may be worth taking a step back and asking what the purpose of labeling things is. For me it's easily finding or filtering things. From that perspective having "editorial" as a label you can use to filter things out is somewhat useful.

**Comment by annevk** [comment]
Yeah, finding similar issues (or ignoring a category of issues) is what I use them for too.

**Comment by geoffcr** [comment]
Curious what "editorial" means here: Clerical/typographic corrections? Implementation guidance? (Political commentary and analysis?) It's a term that I _think_ I understand, but am realizing how context-dependent it can be. 
Even if there's a generally accepted taxonomy in the field, it might be useful for the WHATWG to clarify how each tag or label is used in the context of Living Standards.
$.02 from a Humanities major ....

**Comment by ricea** [comment]
My preference is for not being very prescriptive. This is a tool for spec editors to organise their issues, and it should serve them, not be served by them. We need 5 or 6 words for the label description, then the rest can be left to individual judgement. If it "feels like" editorial, then it is editorial.
